name: CI
on: [push, pull_request]

jobs:
  lint:
    name: Vint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install
        run: |
          pip install vim-vint
          pip install pre-commit
      - name: Run
        run: |
          pre-commit run --all-files || { git diff --color=always && exit 1; }
