name: CI
on: [ push, pull_request ]

jobs:
  lint:
    name: Vint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install
        run: |
          pip install vim-vint
          pip install pre-commit
      - name: Run Vint
        run: |
          pre-commit run --all-files || { git diff --color=always && exit 1; }
  unit-tests:
    name: Unit Tests
    strategy:
      matrix:
        # os: [ windows-2022, ubuntu-20.04 ]
        os: [ ubuntu-20.04 ]
        include:
          # - os: windows-2022
          #   NEOVIM_CONFIG_PATH: ~/AppData/Local/nvim
          - os: ubuntu-20.04
            NEOVIM_CONFIG_PATH: $HOME/.config/nvim
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1.2.6
        with:
          neovim: true
      - name: Ensure plugins directory exists
        env:
          NEOVIM_CONFIG_PATH: '${{ matrix.NEOVIM_CONFIG_PATH }}'
        run: |
          mkdir -p $NEOVIM_CONFIG_PATH/plugins
      - if: ${{ !contains(matrix.os, 'windows') }}
        name: Create a fake code-minimap executable
        # Necessary for minimap.vim to start up
        run: |
          mkdir -p "$HOME/bin"
          ln -s /bin/echo "$HOME/bin/code-minimap"
          echo "$HOME/bin" >> $GITHUB_PATH
      # - if: ${{ contains(matrix.os, 'windows') }}
      #   name: Create a fake code-minimap executable (Windows)
      #   run: |
      #     mkdir -p ~/bin
      #     cp  C:/Windows/System32/doskey.exe ~/bin/code-minimap.exe

      - name: Checkout Testify
        run: |
          git clone --depth 1 https://github.com/dhruvasagar/vim-testify ${{ matrix.NEOVIM_CONFIG_PATH }}/plugins/vim-testify
        env:
          NEOVIM_CONFIG_PATH: '${{ matrix.NEOVIM_CONFIG_PATH }}'
        shell: bash
      - name: Run Unit Tests
        run: |
          echo "not empty file" > testfile
          nvim -c "set rtp+=$NEOVIM_CONFIG_PATH/plugins/vim-testify" -c "set rtp+=./" -S $NEOVIM_CONFIG_PATH/plugins/vim-testify/plugin/testify.vim -S ./plugin/minimap.vim +TestifySuite testfile
        shell: bash
        env:
          NEOVIM_CONFIG_PATH: '${{ matrix.NEOVIM_CONFIG_PATH }}'
